name: Intro to github actions

on:
  push:

jobs:
  hello-world: # job name
    runs-on: ubuntu-latest #
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: build
        run: bun run build

      - name: run the server
        run: |
          bun run preview & 
          sleep 5

      - name: curl the server
        run: curl -I http://localhost:4173
